# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scheduleresponse.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0bguess.proto\x12\ttimetable\x1a\x1fgoogle/protobuf/timestamp.proto"*\n\x08Response\x12\x1e\n\x05items\x18\x02 \x03(\x0b\x32\x0f.timetable.Item"X\n\x04Item\x12\x1b\n\x03raw\x18\x01 \x01(\x0b\x32\x0e.timetable.Raw\x12\x0c\n\x04kind\x18\x02 \x01(\x05\x12%\n\x08\x65nriched\x18\x03 \x01(\x0b\x32\x13.timetable.Enriched"\x99\x02\n\x03Raw\x12\n\n\x02id\x18\x01 \x01(\t\x12%\n\x08location\x18\x02 \x01(\x0b\x32\x13.timetable.Location\x12\r\n\x05title\x18\x03 \x01(\t\x12\x14\n\x0clesson_short\x18\x04 \x01(\t\x12)\n\x05start\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\'\n\x03\x65nd\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12"\n\x07teacher\x18\t \x01(\x0b\x32\x11.timetable.Person\x12\x15\n\rdiscipline_id\x18\r \x01(\t\x12+\n\x07updated\x18\x12 \x01(\x0b\x32\x1a.timetable.TimestampHolder"\xb9\x02\n\x08\x45nriched\x12\n\n\x02id\x18\x01 \x01(\t\x12)\n\x05start\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\'\n\x03\x65nd\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12)\n\ndiscipline\x18\x04 \x01(\x0b\x32\x15.timetable.Discipline\x12*\n\x0blesson_type\x18\x05 \x01(\x0b\x32\x15.timetable.LessonType\x12%\n\x08location\x18\x06 \x01(\x0b\x32\x13.timetable.Location\x12"\n\x07teacher\x18\x07 \x01(\x0b\x32\x11.timetable.Person\x12+\n\x07updated\x18\x08 \x01(\x0b\x32\x1a.timetable.TimestampHolder"=\n\x08Location\x12\x13\n\x0b\x62uilding_id\x18\x01 \x01(\t\x12\x0c\n\x04room\x18\x02 \x01(\t\x12\x0e\n\x06\x63orpus\x18\x03 \x01(\t"b\n\x06Person\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12%\n\x05\x65xtra\x18\x04 \x01(\x0b\x32\x16.timetable.PersonExtra"!\n\x0bPersonExtra\x12\x12\n\npatronymic\x18\x01 \x01(\t"\'\n\nDiscipline\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t"+\n\nLessonType\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tshortname\x18\x02 \x01(\t"<\n\x0fTimestampHolder\x12)\n\x05value\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestampb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "guess_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _RESPONSE._serialized_start = 59
    _RESPONSE._serialized_end = 101
    _ITEM._serialized_start = 103
    _ITEM._serialized_end = 191
    _RAW._serialized_start = 194
    _RAW._serialized_end = 475
    _ENRICHED._serialized_start = 478
    _ENRICHED._serialized_end = 791
    _LOCATION._serialized_start = 793
    _LOCATION._serialized_end = 854
    _PERSON._serialized_start = 856
    _PERSON._serialized_end = 954
    _PERSONEXTRA._serialized_start = 956
    _PERSONEXTRA._serialized_end = 989
    _DISCIPLINE._serialized_start = 991
    _DISCIPLINE._serialized_end = 1030
    _LESSONTYPE._serialized_start = 1032
    _LESSONTYPE._serialized_end = 1075
    _TIMESTAMPHOLDER._serialized_start = 1077
    _TIMESTAMPHOLDER._serialized_end = 1137
# @@protoc_insertion_point(module_scope)
